name: Go

on:
    push:
        branches: ["main"]
        tags:
            - 'v*.*.*'

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v5

            # - name: Check Git version
            #   run: git --version

            - name: Set up Go
              uses: actions/setup-go@v5
              with:
                go-version: '1.24.2'
            
            - name: Build
              run: go build -o server -v ./...

            - name: Test
              run: go test -v ./...

            - name: Create Release
              uses: softprops/action-gh-release@v2
              with:
                files: server
                token: ${{ secrets.GH_PAT }}