name: Go

on:
    push:
        branches: ["main"]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v5

            - name: Check Get version
              run: git --version

            - name: Set up Go
              uses: actions/setup-go@v5
              with:
                go-version: '1.24.2'
            
            - name: Build
              run: go build -v ./...

            - name: Test
              run: go test -v ./...